version: '3'
services:
  app:
    build: .
    command: npm start
    ports:
      - 5000:8080
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    
  db:
    container_name: meubanco
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    


   